### ISSUE TITLE
bad unrecognized type error

### ISSUE THREAD

**Issue by sean-stockholm** [Clojure-Intro-Course/clojure-intro-class#103]
`Error: Function count does not allow unrecognized type core$filter$fn__4574 as an argument.`

it was in code:

`(fn [coll s] (count (filter #(not (re-matches (java.util.regex.Pattern/compile (str s "[1234567890]*")) %) coll))))`

**Comment by sean-stockholm** [comment]
There's also a larger problem ...
the next line reads:
'Found in file null on, or before, line1.`

**Comment by elenam** [comment]
There is something weird with your project,

**Comment by sean-stockholm** [comment]
Looks like a transducer is being passed to count.

**Comment by elenam** [comment]
Since we currently disallow transducers, this is not reproducible.
