### ISSUE TITLE
multi-arg functions different spec conditions

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/clojure-intro-class#116]
The current spec 
```clojure 
(s/fdef reduce
        :args (s/cat :check-funtion ifn? :dummy (s/? ::s/any) :check-seqable seqable?))
```
gives an arity error, not a type error on `(reduce + :not-a-collection)`: 
```
Error: You cannot pass two arguments to a function reduce, need two or three,
in the function call (reduce + :not-a-collection)
```
This is because when the condition for the second argument fails, it expects a third argument that would've made spec pass.

`repeat` and `repeatedly` have the same issue.

**Comment by frogrammer** [comment]
`(reduce 1 [1 2 3]);
; - :two-case fails at ifn?
; - :three-case fails at length3?
(reduce 1)
; - :two-case fails at length2?
; - :three-case fails at length3?
(reduce 1 2 3 3)
; - :two-case fails at length2?
; - :three-case fails at length3?
(reduce + 0 [] 1)
; - :two-case fails at length2?
; - :three-case fails at length3?
(reduce 1 2 3)
; - :two-case fails at length2?
; - :three-case fails at ifn?
(reduce + 3)
; - :two-case fails at seqable?
; - :three-case fails at length3?
(reduce + 2 2)
; - :two-case fails at length2?
; - :three-case fails at seqable?`

**Comment by frogrammer** [comment]
(reduce 1 [1 2 3]);
; - :two-case fails at ifn?
; - :three-case fails at length3?
(reduce 1)
; - :two-case fails at length2?
; - :three-case fails at length3?
(reduce 1 2 3 3)
; - :two-case fails at length2?
; - :three-case fails at length3?
(reduce + 0 [] 1)
; - :two-case fails at length2?
; - :three-case fails at length3?
(reduce 1 2 3)
; - :two-case fails at length2?
; - :three-case fails at ifn?
(reduce + 3)
; - :two-case fails at seqable?
; - :three-case fails at length3?
(reduce + 2 2)
; - :two-case fails at length2?
; - :three-case fails at seqable?
