### ISSUE TITLE
Handle class not found exception

### ISSUE THREAD

**Issue by sean-stockholm** [Clojure-Intro-Course/clojure-intro-class#39]
;(println (clojure.string.split "/home/stock424/Documents/code/clojure-intro-class/src/intro/may2015.clj" #"/"))
;Error: clojure.string.split
;Found in file /home/stock424/Documents/code/clojure-intro-class/src/intro/may2015.clj on line 26 at character 10.
;	intro.core/-main (core.clj line 111)

**Comment by elenam** [comment]
This is a runtime exception, unlike the error on a function name with a correct namespace.

**Comment by elenam** [comment]
Actually, it should be a compilation error. We are classifying it wrong.

**Comment by elenam** [comment]
This is a run-time error because of dynamic class loading.
