### ISSUE TITLE
Handle errors on even? and odd? when argument is a non-integer number

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/clojure-intro-class#42]
Current error: 
Error: Argument must be an integer: 9.8. 
Also, it doesn't seem to shorten the path name:
Found in file C:\Users\elenam\Desktop\Clojure\clojure-intro-class\src\intro\may2015.clj on line 13 at character 1.

- [x] Find out what other cases also require an integer or a non-negative number. 
- [x] Decide if we want to overwrite the functions. Note that `(odd? 9.8)` would complain about `even?`
- [x] Fix the path. 
- [x] Do we want to edit the stacktrace to remove recursive references to even/odd?

**Comment by elenam** [comment]
@sean-stockholm - could you take a look at the file name on this one? I am getting the long name (with slashes and all), not sure why.

**Comment by sean-stockholm** [comment]
I am unable to recreate the long file name:
"Found in file may2015.clj on line 11 at character 1."

**Comment by sean-stockholm** [comment]
we needed to add the argument number to the check-if-integer? call.
