### ISSUE TITLE
Handle invalid token exceptions

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/clojure-intro-class#46]
`(/string ...)` and `(clojure.string/ ...)` are the cases I know. There may be more.

**Comment by sean-stockholm** [comment]
(map #: [1 2 3])
Error: java.lang.RuntimeException: Invalid token: :
Found in file may2015.clj on line 18 at character 9.
	intro.core/-main (core.clj line 114)

**Comment by sean-stockholm** [comment]
(map : [1 2 3])
Syntax error: Invalid token: :
Found in file may2015.clj on line 18 at character 7.
	intro.core/-main (core.clj line 114)

(map :[1 2 3] [1 2 3])
Syntax error: Invalid token: :
Found in file may2015.clj on line 18 at character 7.
	intro.core/-main (core.clj line 114)

**Comment by sean-stockholm** [comment]
(defn # :)
Error: java.lang.RuntimeException: Invalid token: :
Found in file may2015.clj on line 21 at character 10.
	intro.core/-main (core.clj line 114)

**Comment by elenam** [comment]
Suggested wording: 
You cannot use : in this position.

**Comment by elenam** [comment]
Can we make the error message on /string to be "You cannot use / in this position"?

**Comment by sean-stockholm** [comment]
I think I found a new somewhat related error?
(map #/ [1 2 3])

Syntax error: No reader function for tag /
Found in file may2015.clj on line 19 at character 16.
	intro.core/-main (core.clj line 114)

**Comment by sean-stockholm** [comment]
I made the fix you asked, and the tests are passing.
