### ISSUE TITLE
Explore and handle "Reader tag must be a symbol" error 

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/clojure-intro-class#47]
`#2` throws an exception: 
Syntax error: Reader tag must be a symbol
This is a complier error with the RuntimeException cause.

**Comment by sean-stockholm** [comment]
a similar error,
["hi" ## "hello"]

Error: java.lang.RuntimeException: Reader tag must be a symbol
Found in file may2015.clj on line 21 at character 17.
	intro.core/-main (core.clj line 114)

**Comment by sean-stockholm** [comment]
not so similar error, but probably should be,
["hi" ## ]

Error: There is an unmatched delimiter ].
Found in file may2015.clj on line 21 at character 11.
	intro.core/-main (core.clj line 114)
