### ISSUE TITLE
Handle number format exception

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/clojure-intro-class#51]
`1.2.2`
`java.lang.NumberFormatException: Invalid number: 1.2.2`

**Comment by sean-stockholm** [comment]
![capture](https://cloud.githubusercontent.com/assets/9397117/8312054/35afc76c-19a0-11e5-86a9-5e231dd4ac0e.JPG)
This is the error I am getting for it, are ours different, or have you just included the class?

**Comment by elenam** [comment]
Currently we are just throwing the standard Clojure error message. We should include it in the error dictionary and make the number itself boldface (use :arg for this). The wording is fine.
