### ISSUE TITLE
Handle "Can't specify more than 20 params"

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/clojure-intro-class#55]
`(#(+ %22222 1) 2 3)'
Syntax error: Can't specify more than 20 params
Found in file C:\Users\E\Desktop\clojure-intro-class\src\intro\may2015.clj on line 21 at character 1.
	intro.core/-main (core.clj line 114)
cause: RuntimeException

Need to explore this error more and provide handling. 

A suggested wording: 
"A function may not take more than more than 20 parameters"

**Comment by elenam** [comment]
Also need to add the test files. 
Is there any way we can get the function name from the error message?

**Comment by sean-stockholm** [comment]
alright, how was I supposed to add test files? I created them for several of the issues I recently closed, but I do not see any of them in the compilation_errors folder, where I put them.

**Comment by elenam** [comment]
You need to use "git add" to add them. I can see them in your lab account,
so I will add them (since you don't have access to the lab right now).

Elena

On Tue, Jul 7, 2015 at 6:46 PM, Sean Stockholm <notifications@github.com>
wrote:

> alright, how was I supposed to add test files? I created them for several
> of the issues I recently closed, but I do not see any of them in the
> compilation_errors folder, where I put them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Clojure-Intro-Course/clojure-intro-class/issues/55#issuecomment-119375757>
> .
>



-- 
Dr. Elena Machkasova
Associate Professor of Computer Science
Division of Science and Mathematics
University of Minnesota, Morris
Office: Sci 2325
(320) 589-6308
http://cda.morris.umn.edu/~elenam/

**Comment by sean-stockholm** [comment]
I don't think there is a way to get the function name. This is the match I am doing, #"Can't specify more than 20 params"
