### ISSUE TITLE
Add processing for wrong number of args to keyword

### ISSUE THREAD

**Issue by BananaObserved** [Clojure-Intro-Course/clojure-intro-class#66]
(:a) gives "Error: Wrong number of args passed to keyword: :a"

**Comment by BananaObserved** [comment]
The valid number of arguments to a keyword is 1 or 2, where the second arg acts as an else.

**Comment by elenam** [comment]
Need to add test files to the git repo.

**Comment by sean-stockholm** [comment]
Since you added them, and the test is passing, I am closing this issue.
