### ISSUE TITLE
can check-if-transducer? exist?

### ISSUE THREAD

**Issue by sean-stockholm** [Clojure-Intro-Course/clojure-intro-class#81]
so far, I created preconditions for transduce, and added a precondition for into, to fix an arity problem. Currently I am using check-if-function? in the preconditions where I would like to be using check-if-transducer?.

**Comment by elenam** [comment]
I don't think transducers implement any special interface or extend any common class. I looked at all superclasses/interfaces of 'into' (which you can do using (supers (class into))), and didn't find anything that makes it a transducer. 
Your best bet is to just make a list (although one may define their own transducer, I suppose). 
Note that a class of clojure.core 'into' is clojure.core$into
(not sure if you want to list our functions which are corefns.corefns$into or the standard one. 

If you are writing a function that checks the list, please mark it here, but don't close the issue. 

Thanks!

**Comment by elenam** [comment]
Ok, I see what you are saying: not a function that takes a transducer, but a function that is a transducer. I don't know if there is a list of those or an interface. Try playing with class/supers of a known one.
