### ISSUE TITLE
look into errors on 'apply'

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/clojure-intro-class#86]
Is 'apply' a macro? We got some weird error on a fragment when 'apply' was used for one argument; but that code wasn't actually executed. Is it a compiler error?

**Comment by sean-stockholm** [comment]
`(map apply [+ + + +] [[1 2 3] [4 5 6] [7 8 9] [10 11 12]])` works

**Comment by elenam** [comment]
No need to treat it as a special case.
