### ISSUE TITLE
Detecting the only argument

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/clojure-intro-class#87]
In function +, the first argument [1 2] must be a number 
but is a vector.
should be "the argument".

**Comment by sean-stockholm** [comment]
`(empty? :s)` Error: In function empty?, the argument :s must be a sequence but is a keyword.
`(first :e)` Error: In function first, the argument :e must be a sequence but is a keyword.
`(rest :a)` Error: In function rest, the argument :a must be a sequence but is a keyword.
`(next :n)` Error: In function next, the argument :n must be a sequence but is a keyword.
`(seq :w)` Error: In function seq, the argument :w must be a sequence but is a keyword.
`(count :a)` Error: In function count, the argument :a must be a sequence but is a keyword.
`(dissoc :s)` Error: In function dissoc, the argument :s must be a map but is a keyword.
`(odd? "h")` Error: In function odd?, the argument "h" must be an integer number but is a string.
`(even? :e)` Error: In function even?, the argument :e must be an integer number but is a keyword.
`(dec :r)` Error: In function dec, the argument :r must be a number but is a keyword.
`(inc "e")` Error: In function inc, the argument "e" must be a number but is a string.

**Comment by elenam** [comment]
Now that the testing is semi-fixed, you need to add tests for this (and some tests have already been changed to new wording and are passing).

**Comment by sean-stockholm** [comment]
Testing for: 

- [ ]  `empty?`
- [ ]  `first` 
- [ ]  `rest`
- [ ]  `next` 
- [ ]  `seq`
- [ ]  `count` 
- [ ]  `dissoc` 
- [ ]  `odd?` 
- [ ]  `even?` 
- [ ]  `dec`
- [ ]  `inc`

**Comment by sean-stockholm** [comment]
do nested too
