### ISSUE TITLE
Not clearing the atom when we should be

### ISSUE THREAD

**Issue by sean-stockholm** [Clojure-Intro-Course/clojure-intro-class#95]
`(seq? (vec (+ "hi" "hi")))`

Error: In function +, the argument "hi" must be a number but is a string.
Found in file test.clj on, or before, line 12.
	corefns.corefns/+ (corefns.clj line 285)
	intro.test/eval8687 (test.clj line 17)
	intro.core/-main (core.clj line 21)

**Comment by elenam** [comment]
This was caused by changing the atom in a wrong place in handling a single argument. Not really an issue; was fixed when #87 issue was properly done.
